### ISSUE TITLE
Help needed: how to use stick in tokio?

### ISSUE THREAD

**Issue by hkoosha** [libcala/stick#45]
Hi!
I want one thread to read stick events, another one to pick up the latest read event and send it off on a network socket. For networking purposes I'm using tokio, not pasts crate.

The issue is, I can't spawn a task with tokio as `Controller` has an `Rc` inside and rust is unhappy about it not being `Send`.

Here's the gist of the code:
```rust
let mut state = State::new(...);
let mut controller = get_ctl().await;
tokio::spawn(async move {  // => error here => future created by async block is not `Send`
    loop {
        let event = (&mut controller).await; // => also error => has type `Controller` which is not `Send`
        state.event(event);
    }
});
```
(Please forgive any stupid usage of rust / tokio / stick / async, I'm a newbie to both rust and async!)

Can you please guide me on how to achieve this? how should I send a controller through an async task? does this require fundamental changes to `stick` to use `Arc`?

**Comment by hkoosha** [comment]
I cloned the repo and by turning Rc in stick::Controller into Arc, I still had to implement Send manually to make rust happy. I'm definitely doing something wrong here.

**Comment by AldaronLau** [comment]
@hkoosha Thanks for opening this issue!  I just put together https://github.com/libcala/stick/pull/46 which should do the work to make the futures `Send` (apparently a [common issue](https://github.com/libcala/wavy/issues/30) people are running into with my crates, so good to fix).  Luckily this change wasn't too much work, let me know if it works or if you have any questions about what I did.

Once a type is `!Send`, you can't fix that by wrapping it in another type because it still breaks the promise of it being `!Send` if you are moving the type to another thread.  So there are two possible solutions: a) have a thread own that type and communicate via a channel, b) make the type `Send` - if you can prove it `unsafe impl Send {}`, otherwise it can be automatically inferred (in this change I just added it as a requirement of the trait, and needed to replace occurrences of `Rc` with `Arc`).

**Comment by hkoosha** [comment]
Awesome! many many thanks.
I will close this and will follow #46 :D
